#!/usr/bin/env sh

if [ "$SHELL" != "$(brew --prefix)/bin/fish" ]
then
  chsh -s $(brew --prefix)/bin/fish seanstrom
fi

mkdir -p ~/.local/bin/
ln -s $(brew --prefix)/bin/pinentry-mac ~/.local/bin/pinentry-mac
