#!/usr/bin/env sh

if [ "$SHELL" != "$(brew --prefix)/bin/fish" ]
then
  chsh -s $(brew --prefix)/bin/fish seanstrom
fi

ln -s $(brew --prefix)/bin/ ~/.local/bin
ln -s $(brew --prefix)/opt ~/.local/opt

ln -s $(brew --prefix)/bin/ /usr/local/bin
